Repository trustyai-explainability/trustyai-explainability-python, pull requests merged in 2022-12, with the labels that each got.

#125 FAI-898: Add full text feature builder
  src/trustyai/model/__init__.py
  src/trustyai/utils/text.py
  tests/general/test_conversions.py
Labels: bindings

#132 FAI-911: Improve API to declare selections in Python fairness
  src/trustyai/metrics/fairness/group.py
Labels: enhancement, bindings

#133 Expose partial dependence plot in bindings
  src/trustyai/explainers/__init__.py
  src/trustyai/explainers/pdp.py
  tests/general/test_pdp.py
Labels: enhancement, bindings

#136 Add Git changelog automation
  CHANGELOG.md
  cliff.toml
Labels: enhancement, pipeline
