Repository trustyai-explainability/trustyai-explainability-python, pull requests merged in 2022-11, with the labels that each got.

#102 FAI-866: Add Java 17 to CI matrix
  .github/workflows/workflow.yml
Labels: bindings, pipeline

#103 FAI-867: Add Java 9+ Arrow compatibility flags
  src/trustyai/initializer.py
Labels: bug, bindings

#82 FAI-841: Python benchmarks failing since namespace migration
  .github/workflows/benchmarks-merge.yml
  .github/workflows/benchmarks.yml
Labels: bug, pipeline

#104 FAI-878: Update JPype version
  pyproject.toml
  requirements.txt
Labels: dependencies

#106 set normalize_weights to False in LimeExplainer as in Java impl
  src/trustyai/explainers.py
Labels: bug

#107 FAI-879: Sync version with exp-core
  .github/actions/build-arrow/action.yml
  .github/actions/build-core/action.yml
  .github/workflows/benchmarks-merge.yml
  .github/workflows/benchmarks.yml
  .github/workflows/publish.yml
  .github/workflows/workflow.yml
  README.md
  pyproject.toml
  scripts/build.sh
  src/trustyai/__init__.py
  src/trustyai/initializer.py
  src/trustyai/version.py
Labels: bindings, pipeline

#112 FAI-881: Upgrade Pylint version
  pyproject.toml
  requirements-dev.txt
  src/trustyai/explainers.py
  src/trustyai/initializer.py
  src/trustyai/model/__init__.py
  src/trustyai/utils/_tyrus_info_text.py
  src/trustyai/utils/_visualisation.py
  src/trustyai/utils/tyrus.py
Labels: dependencies

#122 Release version 0.2.6
  README.md
  pyproject.toml
  src/trustyai/version.py
Labels: bindings, release

#123 FAI-897: Add bokeh dependency
  pyproject.toml
Labels: bug, bindings, dependencies

#124 Release 0.2.7
  README.md
  pyproject.toml
  src/trustyai/version.py
Labels: bindings, release
